spring.application.name=PerfumeHub

spring.datasource.url=jdbc:mysql://localhost:3306/perfumehub_v2?createDatabaseIfNotExist=true

spring.datasource.username=root
spring.datasource.password=1312

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false

review.service.url=http://localhost:8081